---
version: 2
updates:
  - package-ecosystem: docker
    directory: /devcontainer/
    schedule:
      interval: monthly
    groups:
      Docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      GitHub-Actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      Python:
        patterns:
          - "*"
